name: Continuous deployment

on:
  schedule:
    - cron: '0 0 * * 5,1' # Friday and Monday at midnight

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node }}
      - name: Cache ~/.pnpm-store
        uses: actions/cache@main
        env:
          cache-name: cache-pnpm-store
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ matrix.node-version }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-${{ matrix.node-version }}-build-
            ${{ runner.os }}-
      - run: npm i -g pnpm
      - run: pnpm i
      - run: npm run lint
      - run: npm run test
      - run: npm run build
        
  deploy:
    runs-on: ubuntu-latest
    needs:
      - test-deploy
    strategy:
      matrix:
        node: [14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node }}
      - name: Cache ~/.pnpm-store
        uses: actions/cache@main
        env:
          cache-name: cache-pnpm-store
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ matrix.node-version }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-${{ matrix.node-version }}-build-
            ${{ runner.os }}-
      - run: npm i -g pnpm
      - run: pnpm i
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: 'public'